### ISSUE TITLE
The computation of the tree of changes is slow

### ISSUE THREAD

**Issue by amchiclet** [reprogrammer/cascade#17]

**Comment by reprogrammer** [comment]
We have to be careful about race conditions. We don't want two concurrent tasks modify the same Eclipse project. I can think of two ways to avoid such race conditions:
1. Avoid concurrent modifications to the same Eclipse project by enforcing some ordering on the tasks that apply the changes on the shadow project.
2. Create a fresh shadow project for each change so that the concurrent tasks compute the changes on distinct shadow projects and don't interfere with each other.

I'm not sure which of the above solutions is easier to implement. I'd suggest to go with the one that is easier to implement.
