### ISSUE TITLE
Change node not disabled when the same change node was applied elsewhere

### ISSUE THREAD

**Issue by amchiclet** [reprogrammer/cascade#36]
When a tree has two same change node on a different path, applying one of them should disable both. See picture.

![screenshot from 2014-04-22 18 59 00](https://cloud.githubusercontent.com/assets/728595/2772256/383a6260-ca7a-11e3-8326-4837fff0c511.png)

**Comment by amchiclet** [comment]
See commit comments. This is not entirely fixed. The nodes are correctly disabled, but if the same changes are not visible when a change is applied, it will not be grayed.

**Comment by reprogrammer** [comment]
I reviewed your commits for this issue. I think the problem is that the code looks for related changes only when a change is applied. However, the relation between changes is commutative. That is, if `c1` is related to `c2`, `c2` is also related to `c1`. When the user expands a node, we should check if any of its related changes have been applied. I think the hook to the expansion action is the `getChildren` method. We should add a search in the `getChildren` method to see if any of the children changes are related to an applied change.
